// Real customer reviews for the JB 4 Vertical Bike Rack, pulled from the
// live Okendo reviews widget on https://jbracks.com/products/4-e-bike-rack
// (approved, 4-5 star reviews; long entries trimmed for card display).
// Used by ReviewsCarousel on /lp-vertical-bike-racks for expanded social proof.

export type ProductReview = {
  rating: number;
  title: string;
  body: string;
  author: string;
  variant: string;
};

export const productReviews: ProductReview[] = [
  {
    rating: 5,
    title: "Fantastic bike rack",
    body: "I have put this together and used it several times now. Seems to be very good quality! I did order the rack first to decide if I needed the shock absorber option, then quickly realized that I would need it as an older person. So I ordered the now only available double strut system to find I had to re configure the…",
    author: "John B.",
    variant: "Leaf Green / Leaf Green",
  },
  {
    rating: 4,
    title: "Sturdy bike rack",
    body: "I purchased a 4 bike rack. I recently used it to transport 4 bikes on a camping trip from Ohio to Michigan. It was easy to put together. I could have used an extra hand on a couple of steps. My only real issue in building the rack was the holes in the bottom tube for the lower bar didn't match the diagram. The diagram…",
    author: "Matthew A.",
    variant: "Black / Black",
  },
  {
    rating: 5,
    title: "A really good rack at a reasonable price.",
    body: "I love that JB Rack provided numerous instructional materials which were very helpful; however, my particular rack differed slightly from models depicted. I recommend JB Racks make it easier for new buyers to distinguish their model from others, and to make clear the various assembly details of the different models.…",
    author: "Bert T.",
    variant: "Black / Black",
  },
  {
    rating: 4,
    title: "4 bike mount rack",
    body: "It’s a strong, rugged bike rack. The video and written instructions that are available to the consumer, and posted on the web site are for a “Canadian” model. Makes assembly a lot more difficult. Very confusing and misleading. I didn’t realize the hydraulics don’t come with the rack, so I had to spend an additional…",
    author: "Andy S.",
    variant: "Black / Black",
  },
  {
    rating: 4,
    title: "A good bike rack for 6 bikes",
    body: "We replaced a 5 rack with this 6 rack. Bikes are easy to load. The assembly instructions were not current with the parts included, however, customer service sorted that out. It is a bit rocky so I have added tie down straps for extra rigidity",
    author: "Larry C. W.",
    variant: "Black / Black",
  },
  {
    rating: 4,
    title: "Good value",
    body: "It gets the job done. Installation was pretty easy, but instructions were related to the older version which was a little confusing. Many extra parts were left over after installation. The rack does its job well and holds the bikes in place just fine. I will say with four bikes on the rack, its a two person job to…",
    author: "Travis W.",
    variant: "Black / Black",
  },
  {
    rating: 5,
    title: "Amazing Bike Rack",
    body: "With a family of 6 and everyone now on bikes I needed a solution that didn't break the bank and offered quality features. In steps JB racks, I did look at other brands but all were about twice the price. Upon arrival and inspection of the parts. I must say the quality is top notch, all the steel bars, nuts, bolts, and…",
    author: "Shan S.",
    variant: "Leaf Green / Leaf Green",
  },
  {
    rating: 5,
    title: "JB 5 Bike Rack",
    body: "Great sturdy rack, easy to build!",
    author: "David B.",
    variant: "",
  },
  {
    rating: 5,
    title: "Excellent Bike Rack",
    body: "I have used it with 3 bikes on so far and it is super easy to load and take off the bikes; there is no adjusting and readjusting to get the bikes to fit. I also really like the fact that it lays flat behind the van when the struts are not installed, making it convenient to get in the back of the van without removing…",
    author: "Michael O.",
    variant: "Leaf Green / Leaf Green",
  },
  {
    rating: 5,
    title: "2024 Tacoma Rack",
    body: "Well built and designed rack. No complaints on build or quality. Only thing I would suggest is that with the 2024 Tacoma Toyota made the receiver wider so it needed a longer hitch bolt which JB racks made it right. If you could select what length hitch pin you needed so you wouldn’t have to wait for the correct on to…",
    author: "Brad B.",
    variant: "Leaf Green / Leaf Green",
  },
  {
    rating: 5,
    title: "Still in box",
    body: "I haven’t put it together yet but the shipment and delivery was good.",
    author: "Anthony L.",
    variant: "Black / Black",
  },
  {
    rating: 4,
    title: "Good so Far",
    body: "This rack does not appear to be a disappointment so far from a manufacturing perspective. It appears solidly built and well-designed. I have not had the opportunity to try it out in the mountain yet because the snow and weather have prevented it. The reason it gets 4 stars is because the video instructions for…",
    author: "Brian H.",
    variant: "Black / Black",
  },
  {
    rating: 4,
    title: "Assembly guidance needs revision",
    body: "The rack is great once assembled but the assembly experience is hampered by poor instructions that you have to watch several times over. There is no labelling on components and there was heaps of left overs. The assembly video also meant I assembled a single strut set up until such time I realised there was a second…",
    author: "Blake M.",
    variant: "",
  },
  {
    rating: 5,
    title: "4 Bike Rack",
    body: "Great value - well built",
    author: "Danie S.",
    variant: "",
  },
  {
    rating: 4,
    title: "great product, alot of assembly required",
    body: "Excellent product, fair price, good quality, alot of assembly required.",
    author: "Dean M.",
    variant: "",
  },
  {
    rating: 5,
    title: "Loving it!",
    body: "I’ve had my rack for a few weeks and am absolutely using the heck out of it! I especially love how easy it is to lad my bikes.",
    author: "Michael J.",
    variant: "Leaf Green / Leaf Green",
  },
  {
    rating: 4,
    title: "Good Rack. Not as stable as I’d like",
    body: "Overall the experience wasn’t bad. I ordered the 6 bike rack and it came in two shipments. First one arrived early. Second never left shipper. Still shows pending one I like that up. Had plans for the weekend when it would all be here but it happens. After I had assembled the rack through videos I noticed the lady…",
    author: "Miguel M.",
    variant: "Velo Turquoise / Velo Turquoise",
  },
  {
    rating: 5,
    title: "Great bike rack and fantastic service",
    body: "Great bike rack, quality build and excellent value for money. Also would say the customer service is exceptional.",
    author: "Angus B.",
    variant: "",
  },
  {
    rating: 5,
    title: "4 bike rack",
    body: "I did a lot of searching and enquiring regarding bike racks, I ended up buying a JB Rack because of several reasons. The price is excellent, the story behind them is inspiring, the rack itself is strong and durable, I added the strut for easier lowering, overall I highly recommend them to anyone searching for a great…",
    author: "Ryan J.",
    variant: "",
  },
  {
    rating: 5,
    title: "Super fast delivery, great product 👍",
    body: "Ordered the rack and garage stand the Sunday night, delivered Tuesday morning. Easy to assemble, looks great and it was value for money.",
    author: "Carl Z.",
    variant: "",
  },
  {
    rating: 5,
    title: "Great company",
    body: "They respond very fast to all my questions and work to find a solution.",
    author: "Benjamin F.",
    variant: "",
  },
  {
    rating: 5,
    title: "Easy to find what you want.",
    body: "Simple and not to many choices",
    author: "Zachary Q.",
    variant: "",
  },
  {
    rating: 4,
    title: "Stand",
    body: "Quick and easy to get the bike on and off. Would like to see more a well/holder for lower wheel rather than just the one sided bracket. Would still recommend rack though. Definitely worth purchasing stand with rack.",
    author: "Jacinta G.",
    variant: "",
  },
  {
    rating: 4,
    title: "Great rack, needs more durable rubber straps",
    body: "The rack has been great. It rides fairly well and doesn't bounce around too much. My only issue with the rack is the rubber straps and the nylon pedal straps. The first time we used the rack we tore through one of the rubber straps due to the sharp finish on the hook. It would be better if the hooking system were…",
    author: "Kenny R.",
    variant: "",
  },
  {
    rating: 5,
    title: "In racks",
    body: "Item came super quick, really good quality and awesome price point",
    author: "Shaun T.",
    variant: "",
  },
  {
    rating: 5,
    title: "👍🏻👍🏻👍🏻",
    body: "Top rack, easy to build",
    author: "marc-paul d. g.",
    variant: "",
  },
  {
    rating: 5,
    title: "Superb Product and Service.",
    body: "Excellent product and assembly tutorial. Service was great and extremely helpful when enquiring information about additional products.",
    author: "Justin V.",
    variant: "",
  },
  {
    rating: 4,
    title: "Good but not perfect",
    body: "Allot of my items came scratched pretty heavily. One looked like it was dragged across the asphalt. It wasn’t done in shipping as the boxes were all pristine and the parts were bubble wrapped AF! It all works though and is still a great deal for the price. Make sure the slow fold strut is part of your package too! It…",
    author: "Tyson W.",
    variant: "",
  },
  {
    rating: 5,
    title: "works well",
    body: "works well with a tow hitch for trailer also",
    author: "les v.",
    variant: "",
  },
  {
    rating: 4,
    title: "3 Bike Rack",
    body: "Excellent quality. Seems to be very durable and sturdy compared to other bike racks that we’ve purchased in the past. However, when the rack arrived it was missing the small tire stay tab on the lower portion of the rack. I contacted customer service and a new lower crossbar (with tabs) was sent ASAP. But, when we…",
    author: "Elliot E.",
    variant: "",
  },
  {
    rating: 4,
    title: "It’s ok.",
    body: "Seems sturdy, no problem with bike movement on forest roads, or at least acceptably so. The wheel hoops pain chips easily with no rocks in the tires. Also, after the first rainstorm, rust has begun to appear on the bottom of the wheel hoops where welded to their base plate. Before installation, highly recommended to…",
    author: "Chad A.",
    variant: "",
  },
  {
    rating: 4,
    title: "Great product and service",
    body: "They were great with my questions and helping. Down side is only a video instructions and no product part were labeled. Would have been helpful to have sized bolts labeled.",
    author: "Jessica B.",
    variant: "",
  },
  {
    rating: 5,
    title: "Works well",
    body: "Great stand and rack! Directions are hard to follow but doable if you know what you’re doing!",
    author: "Jessica B.",
    variant: "",
  },
  {
    rating: 4,
    title: "Great Rack!",
    body: "Only thing missing in my opinion, is a pinch bolt to lock rack into hitch.",
    author: "Stephen S.",
    variant: "",
  },
  {
    rating: 5,
    title: "Love the bike rack",
    body: "I love the bike rack, but I didn't get the strut. I just got an email if I order today the 150 strut is free.",
    author: "Bruce M. A.",
    variant: "",
  },
  {
    rating: 5,
    title: "Easy",
    body: "Easy loading and unloading.",
    author: "John M.",
    variant: "",
  },
  {
    rating: 4,
    title: "Very well built",
    body: "I got the six bike rack and am happy with it. It is very well built and easy to load. The only problem was I had to get an extension otherwise it sits too close to my camper and Durango. So it would be nice if the receiver hitch part was a 2 or 3 inches longer.",
    author: "Jacinda M.",
    variant: "",
  },
  {
    rating: 4,
    title: "JB 5 bike rack",
    body: "Powder coat is a little thin and chipped before I put it together (not a major issue) as I have paint that stops rust from starting. I have what seems to be the newest version and it seems solid and even designed for new accessories coming out soon. Overall this seems to be a good rack. I hauled 4 bikes just fine…",
    author: "Joshua P.",
    variant: "",
  },
  {
    rating: 5,
    title: "Fits well. No issues. Perfect design.",
    body: "Fits well. No issues. Perfect design.",
    author: "Russell W.",
    variant: "",
  },
  {
    rating: 5,
    title: "Amazing and top quality - Only one issue with the tow bar bolt but found a resolution to it.",
    body: "Highly recommend. The only issue I have is the pin bolt doesn't line up well that goes into the tow bar bit. The holes in the bike rack frame have nuts welded in. This is not required and appears to be off center and you can't unweld it unfortunately. I can't even get a standard pin in because of the nut thread. I…",
    author: "Russell W.",
    variant: "",
  },
  {
    rating: 5,
    title: "Great Bike Rack",
    body: "Great bike rack, easy to assemble, the video instructions are easy to follow. Easy to load bikes on and off. The rack and accessories are very good value for money! Would highly recommend!",
    author: "Scott G.",
    variant: "",
  },
  {
    rating: 5,
    title: "Good rack, great service",
    body: "Rack is as described and works well. I also messed up my order a little and JB Racks fixed it without an issue. Highly recommend",
    author: "Daniel W.",
    variant: "",
  },
  {
    rating: 5,
    title: "4 bike rack",
    body: "Awesome rack, durable, mostly easy assembly, great customer service and assistance",
    author: "Elizabeth C.",
    variant: "",
  },
  {
    rating: 4,
    title: "I'm glad I upgraded to the e-bike rack",
    body: "Seems a bit flimsy at the base tube and upright plates. Sways on the road with 2 adult bikes and 3 kids bikes. None are e-bikes so that makes me nervous for longer trips. I will try to update at month end after my first moderate trip.",
    author: "Zachary C.",
    variant: "",
  },
  {
    rating: 4,
    title: "Thinking Forward",
    body: "I took my new JB Rack on an 800 mile trip two days after I got it. I was a bit nervous because the rack seemed to shake quite a bit. 50 miles into my trip, one of the straps broke and my bike bounced out of the wheel basket, but fortunately got hung up on the tire tab. The strap wasn't put on overly tight. It matched…",
    author: "Enoch H.",
    variant: "",
  },
  {
    rating: 4,
    title: "Good rack but a few improvements needed",
    body: "I like the rack but a few improvements would make it great. The tabs that serve as stops for the rear tires are of thin metal that tend to bend. The straps used at the bottom are a bit jenky. A redesign to include straps as used in the upper tire hoops would be better I think. My unit was delivered with the packaging…",
    author: "Ryker W.",
    variant: "",
  },
  {
    rating: 5,
    title: "Great Bike Holder",
    body: "Well built and sturdy. Absolutely glad the family got this bike rack.",
    author: "Lindsey T.",
    variant: "",
  },
  {
    rating: 5,
    title: "Feedback on rack",
    body: "Gods communication with updates and a reasonable delivery time. After the rack was delivered, I noticed the tow hitch did not fit my vehicle (needed a rounded hitch, not square). I sent the query via email which was rectified in a reasonabletime frame & I received a rounded hitch as a replacement. Downside:…",
    author: "Nathan G.",
    variant: "",
  },
  {
    rating: 5,
    title: "Great Function Product",
    body: "Although I've not gotten all my parts that I originally ordered the parts I do have are very well put together and holds the Bikes firmly. The customer service is great at getting back to you with updates on the locations of each originally ordered part(s)",
    author: "Paul Y.",
    variant: "",
  },
  {
    rating: 5,
    title: "bike rack",
    body: "surprisingly good build quality for the price. took it on 1 trip so far, 2nd one tomorrow. does wobble left to right a little more than i would of thought, but ive never had a bike rack before, so could be normal. got to remember to slow down on speed bumps . overall, very happy with it.",
    author: "Mark domotor D.",
    variant: "",
  },
  {
    rating: 4,
    title: "Good value",
    body: "Rack works well . Assembly was not easy and a part was not correct. Got it sorted quickly which was good.",
    author: "Matthew G.",
    variant: "",
  },
  {
    rating: 4,
    title: "5 Bike Rack and Shed Stand - the good, the bad & the ugly",
    body: "So I have been running with my JB Racks 5 bike rack for about 6 months now and thought it is a good time to come and provide an honest review of my experience with it so far. I bought the 5 bike rack and shed stand package to use for my 2 beach cruiser bikes and 3 kids bikes which is mounted on an SUV and also behind…",
    author: "Jacob",
    variant: "",
  },
  {
    rating: 5,
    title: "Took forever but finally have it!",
    body: "We had some shipping problems and a lot of communication with customer service. But, they came through and I got my rack. It took about a month. They did offer me a free accessory as an apology.",
    author: "Rebecca S.",
    variant: "",
  },
  {
    rating: 5,
    title: "Awesome looking and quality product",
    body: "Awesome looking and quality product, feels solid, shipping was a pain due to warehouse issue but it was resolved. Assembly was easy with their instructional video",
    author: "Christian L.",
    variant: "",
  },
  {
    rating: 4,
    title: "Opening rear vehicle door",
    body: "The main body tilt plates could be made Lower you can open your rear door of a An FJ Cruiser .. I need an extension to Drop the while rack so I can open the rear door",
    author: "Thomas G.",
    variant: "",
  },
  {
    rating: 5,
    title: "New 6 Bike Rack",
    body: "The new rack is awesome!! Super easy to assemble and even eaiser to use for loading and unloading with the gas strut!! Love it",
    author: "Ryan A.",
    variant: "",
  },
  {
    rating: 5,
    title: "So far so good",
    body: "Was easy to put together with the video seem very solid after one use. Bike went on easy, they did not touch each other. So im happy with the JB 4 bike rack",
    author: "Sandy M.",
    variant: "",
  },
  {
    rating: 5,
    title: "Yes, you can modify this rack to a 2 bike version!",
    body: "We love this rack but it is heavy - even the 3 bike version. JB Racks said they'd help me customizing this product for 2 bikes but didn't get back to me. No matter, I went ahead and removed the top bar extensions and left sided of the bottom bar extension (as well as 14 bolts which were no longer required). Great…",
    author: "James B.",
    variant: "",
  },
  {
    rating: 5,
    title: "5 Stars",
    body: "Rack took me about an hour to build, but now its done Im happy. They need to improve delivery and assembly but I would still recommend. Other options were way too expensive.",
    author: "Fegus L.",
    variant: "",
  },
  {
    rating: 5,
    title: "JB -  4 Bike Rack",
    body: "I have received and built rack and fitted to vehicle without any real problems. The instruction video is good once you find it and PDF version on line is helpful back up. The overall quality is good, for the price point. Only real fitting issue is the Left side lower wheel angle bracket dont seem to align under the…",
    author: "Stuart C.",
    variant: "",
  },
  {
    rating: 5,
    title: "Amazing Bike Rack",
    body: "My truck looks monstrous after installing this bike rack. Highly recommended!!!",
    author: "Edgar P.",
    variant: "",
  },
  {
    rating: 5,
    title: "Love the bike rack!",
    body: "Very happy with the purchase process of JB racks 6 place bike rack!",
    author: "Phil S.",
    variant: "",
  },
  {
    rating: 5,
    title: "Great bike rack!",
    body: "Love the rack, very happy with it and I would recommend it. Couple things to note. Like most people have said, packaging allows for some damage in delivery and instructions to assemble need to be better but if you take your time and look at pictures you will be fine. The upper head (T-bar) is a little loose when…",
    author: "Phil S.",
    variant: "",
  },
  {
    rating: 5,
    title: "I super love it.",
    body: "This bike rack is simply amazing. I will recommend this to all my friends.",
    author: "Edgar P.",
    variant: "",
  },
  {
    rating: 5,
    title: "Rack works perfect",
    body: "Handled the rough off road trip I did, didnâ€™t move around too much. Only thing I would recommend is an optional number plate holder that mounts the plate out past the bikes.",
    author: "Joshua R.",
    variant: "",
  },
  {
    rating: 5,
    title: "Rack works perfect",
    body: "Handled the rough off road trip I did, didn’t move around too much. Only thing I would recommend is an optional number plate holder that mounts the plate out past the bikes.",
    author: "Joshua R.",
    variant: "",
  },
  {
    rating: 4,
    title: "Couple minor issues",
    body: "Great Bike rack, only two little issues. I think the instruction manual could be better in explaining installation of the product. Also found the powder coat on the draw bar insert was to thick and I had to grind down the each corner for it to slide in properly. Other than that it’s a great bike rack and great price .…",
    author: "Bryn H.",
    variant: "",
  },
  {
    rating: 5,
    title: "Great value",
    body: "Great value for both the rack and shed stand. But he instructions need a lot of work. Kind of just figured out. If you are a bit mechanically savvy should be ok.",
    author: "Minkyu P.",
    variant: "",
  },
  {
    rating: 5,
    title: "First vertical bike rack I have purchased",
    body: "Prior to purchase I read numerous online reviews. One of the comparison reviews gave the JB rack a very positive rating. Having never built a vertical bike rack before it did take a bit of time to construct. One review claimed it took them 90 minutes. Definitely takes longer than 90 minutes. The written instructions…",
    author: "Arunas B.",
    variant: "",
  },
  {
    rating: 5,
    title: "Great Rack.  Bad packing",
    body: "So this review is coming from the USA. The rack now built took its maiden voyage yesterday . The rack itself is great. Worked flawlessly with 5 full bike loaded. I love the piston. ( must have). The downside is the packaging of the rack itself for shipping (probably fedex fault) but this thing got destroyed during…",
    author: "Douglas p.",
    variant: "",
  },
];
